
version: "3"
services:
  db:
    image: mysql:8

    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'django_backend'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
#    container_name: mysql_server
    networks:
      - django_site
    volumes:
      - /db:/var/lib/mysql
    expose:
      - 3306
      - 33060

  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    depends_on:
      - db
    networks:
      - django_site
    container_name: django_backend

    command:
      - /bin/bash
      - -c
      - |
       python manage.py migrate
       python manage.py runserver

networks:
  django_site:
    driver: bridge




